name: generate-site

on:
  pull_request: {} 
  push:   
    branches:
      - "main"

permissions:
  contents: write

jobs:
  Update:
    name: Build and Deploy Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Update Site
        run: |
          docker build -t latex2md .
          docker run --rm -i -v $PWD:/code latex2md
          git status

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build --future

      - name: Deploy to gh-pages
        if: (github.event_name == 'push')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
